services:
  - type: web
    name: sign-translate
    env: node
    repo: https://github.com/<your-username>/translate
    branch: main
    workingDirectory: translate-master    # <-- thêm dòng này
    buildCommand: npm install --omit=dev && npm run build:full
    startCommand: node dist/sign-translate/server/server.mjs
    envVars:
      - key: PORT
        value: 3000
